import type {
  TrackBenchmarkCaseV4,
  TrackBenchmarkSummaryV4,
  TrackPolicyV4,
  TrackV4DomainId,
  TrackV4HandlingOutcome,
} from "./benchmark-schema.js";

function basePolicy(): TrackPolicyV4 {
  return {
    scope: {
      includeSkillIds: [],
      excludeSkillIds: [],
      includeCategories: [],
      excludeCategories: [],
    },
    allocation: {},
    pacing: {},
    sessionComposition: {},
    difficulty: { mode: "adaptive" },
    progression: { mode: "linear" },
    review: { scheduler: "sm5", aggressiveness: "balanced" },
    adaptation: {},
    cadence: [],
    contentSource: { realItemsFirst: true },
  };
}

function withPolicy(overrides: Partial<TrackPolicyV4>): TrackPolicyV4 {
  const base = basePolicy();
  return {
    ...base,
    ...overrides,
    scope: { ...base.scope, ...(overrides.scope ?? {}) },
    allocation: { ...base.allocation, ...(overrides.allocation ?? {}) },
    pacing: { ...base.pacing, ...(overrides.pacing ?? {}) },
    sessionComposition: { ...base.sessionComposition, ...(overrides.sessionComposition ?? {}) },
    difficulty: { ...base.difficulty, ...(overrides.difficulty ?? {}) },
    progression: { ...base.progression, ...(overrides.progression ?? {}) },
    review: { ...base.review, ...(overrides.review ?? {}) },
    adaptation: { ...base.adaptation, ...(overrides.adaptation ?? {}) },
    cadence: overrides.cadence ?? base.cadence,
    contentSource: { ...base.contentSource, ...(overrides.contentSource ?? {}) },
  };
}

interface StressUserCaseConfig {
  intentId: string;
  domainId: TrackV4DomainId;
  benchmarkClass: TrackBenchmarkCaseV4["benchmarkClass"];
  expectedOutcome: TrackV4HandlingOutcome;
  policyFamilies: TrackBenchmarkCaseV4["policyFamilies"];
  request: string;
  goldPolicy?: TrackPolicyV4;
  unsupportedReason?: string;
}

function stressUserCase(config: StressUserCaseConfig): TrackBenchmarkCaseV4 {
  return {
    intentId: config.intentId,
    domainId: config.domainId,
    benchmarkClass: config.benchmarkClass,
    policyFamilies: config.policyFamilies,
    naturalLanguageRequests: [config.request],
    goldPolicy: config.goldPolicy,
    clarificationExpected: config.expectedOutcome === "clarify",
    repairAllowed: config.expectedOutcome === "clarify" || config.expectedOutcome === "repaired",
    expectedOutcome: config.expectedOutcome,
    unsupportedReason: config.unsupportedReason,
  };
}

const codingStressCases: TrackBenchmarkCaseV4[] = [
  stressUserCase({
    intentId: "stress-dsa-graphs-only-rambly",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["scope"],
    request: "I'm not asking for a grand plan here. I keep dodging graphs, then I regret it, so for now just pin me to graph work and don't be cute about it.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["graphs"], excludeSkillIds: [], includeCategories: ["graphs"], excludeCategories: [] },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-graphs-over-trees-ramble",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["scope", "allocation"],
    request: "If we're splitting attention, tilt it pretty hard toward graphs over trees. Call it 70/30 if you need numbers.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["graphs", "trees"], excludeSkillIds: [], includeCategories: ["graphs", "trees"], excludeCategories: [] },
      allocation: { skillWeights: { graphs: 0.7, trees: 0.3 } },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-workday-weekend-window",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["pacing"],
    request: "Realistically I can squeeze in 15 on workdays. Weekends are looser, so give me 30 there and stop pretending I have surprise extra time midweek.",
    goldPolicy: withPolicy({
      pacing: { weekdayMinutes: 15, weekendMinutes: 30 },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-four-times-week",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["pacing"],
    request: "I don't need this every day. Four sessions a week is enough if they're actually purposeful.",
    goldPolicy: withPolicy({
      pacing: { sessionsPerWeek: 4 },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-more-old-than-new",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition", "review"],
    request: "Stop acting like novelty is the answer. I need more old stuff than fresh stuff for a bit or this just won't stick.",
    goldPolicy: withPolicy({
      sessionComposition: { reviewShare: 0.7, newShare: 0.3 },
      review: { scheduler: "sm5", aggressiveness: "balanced", interleaveOldAndNew: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-easy-first-then-medium",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty"],
    request: "Don't open with hard mode. Start easy, let me get my feet under me, and then bring mediums in later.",
    goldPolicy: withPolicy({
      difficulty: {
        mode: "staged",
        stages: [
          { afterSessions: 0, targetBand: "easy" },
          { afterSessions: 4, maxBand: "medium" },
        ],
      },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-basics-before-fancy",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression", "scope"],
    request: "Before you make this fancy, lock the basics. I don't want advanced graph weirdness until the core patterns stop wobbling.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: [], excludeSkillIds: [], includeCategories: [], excludeCategories: [], fundamentalsOnly: true },
      progression: { mode: "mastery_gated", prerequisitesFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-overdue-must-return",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["review"],
    request: "If something is overdue, I want it dragged back until it gets done. Don't let stale review just disappear because the planner got optimistic.",
    goldPolicy: withPolicy({
      review: { scheduler: "sm5", aggressiveness: "aggressive", includeOverdueEverySession: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-fake-interview-cadence",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["cadence", "session_composition"],
    request: "Every fifth session, run me through something fake-interview-ish. I still want normal work otherwise, but that cadence should be there.",
    goldPolicy: withPolicy({
      sessionComposition: { mockShare: 0.2 },
      cadence: [{ kind: "every_n_sessions", bucket: "mock", everyNSessions: 5 }],
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-real-first-synthetic-later",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source", "adaptation"],
    request: "Use the real pool first. If we run that thin, then fine, synthesize filler variants, but not before.",
    goldPolicy: withPolicy({
      adaptation: { onSeedPoolLow: "allow_generation" },
      contentSource: { generatedAllowed: true, generatedOnlyAsFallback: true, realItemsFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-generated-drills-only-no-assessment",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source", "session_composition"],
    request: "Synthetic content is fine for drills. It is not fine for anything that smells like assessment.",
    goldPolicy: withPolicy({
      sessionComposition: { drillShare: 0.4 },
      contentSource: { generatedAllowed: true, generatedForDrillsOnly: true, noGeneratedForAssessment: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-seed-only-hard-boundary",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source"],
    request: "No synthetic variants. Stick to the real catalog only, even if that makes the pool tighter.",
    goldPolicy: withPolicy({
      contentSource: { seedOnly: true, generatedAllowed: false, realItemsFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-back-off-if-cratering",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty", "adaptation"],
    request: "If I crater for a few sessions in a row, back it off. I do not want the system responding by turning the dial up.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-push-when-cruising",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty", "adaptation"],
    request: "If I'm cruising, then yes, push harder. I don't want to sit in easy mode forever once it's obviously too soft.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", pushOnSuccess: true },
      adaptation: { onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-overdue-review-focus",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["adaptation", "session_composition", "review"],
    request: "If overdue review starts piling up, stop pretending we can outrun it. Shift hard into review focus until that load comes down.",
    goldPolicy: withPolicy({
      sessionComposition: { reviewShare: 0.8, newShare: 0.2 },
      review: { scheduler: "sm5", aggressiveness: "balanced", includeOverdueEverySession: true },
      adaptation: { onOverdueLoad: "review_focus" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-single-topic-until-solid",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "For now keep sessions single-topic. Mixing everything together is just making the weak spots harder to see.",
    goldPolicy: withPolicy({
      sessionComposition: { mixedSessions: false },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-mixed-practice-explicit",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Actually, once I stabilize, I do want mixed practice. I don't want each session to feel like a silo forever.",
    goldPolicy: withPolicy({
      sessionComposition: { mixedSessions: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-cap-new-items",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Cap fresh material at 2 new items a session. More than that and the review debt gets stupid.",
    goldPolicy: withPolicy({
      sessionComposition: { maxNewItemsPerSession: 2 },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-warmup-first-explicit",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Give me a warmup at the front. I don't want to walk cold into the hardest thing on the board.",
    goldPolicy: withPolicy({
      sessionComposition: { warmup: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-breadth-first-pass",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "I want a breadth-first pass before we go deep. Touch the landscape, then dig.",
    goldPolicy: withPolicy({
      progression: { mode: "breadth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-depth-first-pass",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "No survey course energy. Go depth-first and stay there long enough for it to matter.",
    goldPolicy: withPolicy({
      progression: { mode: "depth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-spiral-looping",
    domainId: "coding-interview-patterns",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "I'd rather keep looping back around than pretend one clean pass means the topic is done.",
    goldPolicy: withPolicy({
      progression: { mode: "spiral" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-shaky-stuff-vague",
    domainId: "coding-interview-patterns",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["scope", "allocation", "adaptation"],
    request: "Could you mostly keep me on the shaky stuff? I'm being vague on purpose because I don't know whether I mean confidence or failure history.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: [], excludeSkillIds: [], includeCategories: [], excludeCategories: [], weakAreasOnly: true },
      allocation: { weakAreaBias: "strong" },
      adaptation: { onRepeatedFailures: "rehab_focus" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-weekends-carry-load-vague",
    domainId: "coding-interview-patterns",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["pacing", "session_composition"],
    request: "Have weekends carry more of the load. I don't actually know whether I mean more time, more review, or harder work.",
    goldPolicy: withPolicy({
      pacing: { weekendMinutes: 30 },
      sessionComposition: { reviewShare: 0.6 },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-cycle-back-ambiguous",
    domainId: "coding-interview-patterns",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["progression", "review"],
    request: "I want things to cycle back around more, but I mean that in a fuzzy way. Not sure if that means spiral progression or just heavier review.",
    goldPolicy: withPolicy({
      progression: { mode: "spiral" },
      review: { scheduler: "sm5", aggressiveness: "balanced", interleaveOldAndNew: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-important-stuff-ambiguous",
    domainId: "coding-interview-patterns",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["scope", "allocation"],
    request: "Stay on the important stuff. That's probably not enough information, but that's honestly how I'd say it.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["graphs", "trees"], excludeSkillIds: [], includeCategories: ["graphs", "trees"], excludeCategories: [] },
      allocation: { breadthVsDepth: "depth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-turn-it-up-weekends-ambiguous",
    domainId: "coding-interview-patterns",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["pacing", "difficulty"],
    request: "Turn it up on weekends. I know that's vague; I don't know whether I mean harder or just longer.",
    goldPolicy: withPolicy({
      pacing: { weekendMinutes: 45 },
      difficulty: { mode: "fixed", targetBand: "hard" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-more-interview-ish-ambiguous",
    domainId: "coding-interview-patterns",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["cadence", "difficulty", "session_composition"],
    request: "Can you make this feel more interview-ish? I don't know whether that means mocks, timing pressure, or just harder prompts.",
    goldPolicy: withPolicy({
      sessionComposition: { mockShare: 0.2 },
      difficulty: { mode: "fixed", targetBand: "hard" },
      cadence: [{ kind: "every_n_sessions", bucket: "mock", everyNSessions: 5 }],
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-push-not-wreck-repair",
    domainId: "coding-interview-patterns",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Push me, just don't wreck me. That's the whole brief.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-push-not-fry-repair",
    domainId: "coding-interview-patterns",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Stretch me, but don't fry me. I want challenge without getting smoked.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-honest-but-learning-repair",
    domainId: "coding-interview-patterns",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "review"],
    request: "Be honest about how I'm doing, but still leave room for me to learn. I know that isn't a clean track-policy sentence.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", backoffOnStruggle: true, pushOnSuccess: true },
      review: { scheduler: "sm5", aggressiveness: "balanced" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-challenge-not-underwater-repair",
    domainId: "coding-interview-patterns",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Challenge me, but not to the point where I feel underwater every single session.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-dsa-tired-after-work-unsupported",
    domainId: "coding-interview-patterns",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "When I'm wiped out after work, have the plan quietly dial itself down without me saying anything.",
    unsupportedReason: "Fatigue-aware context is out of scope for deterministic track policy.",
  }),
  stressUserCase({
    intentId: "stress-dsa-stress-level-unsupported",
    domainId: "coding-interview-patterns",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "Match the plan to my stress level in the background.",
    unsupportedReason: "Stress-aware adaptation is not represented in V4 track policy.",
  }),
  stressUserCase({
    intentId: "stress-dsa-sleep-quality-unsupported",
    domainId: "coding-interview-patterns",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["pacing"],
    request: "If I slept badly the night before, just make the plan lighter on its own.",
    unsupportedReason: "Sleep-aware pacing is outside the V4 request boundary.",
  }),
  stressUserCase({
    intentId: "stress-dsa-calendar-unsupported",
    domainId: "coding-interview-patterns",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["cadence", "pacing"],
    request: "Please use my calendar and shuffle the plan around meetings automatically.",
    unsupportedReason: "External calendar state is not modeled in V4 track policy.",
  }),
  stressUserCase({
    intentId: "stress-dsa-mood-unsupported",
    domainId: "coding-interview-patterns",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "Make it easier when I'm in a bad mood and harder when I'm feeling sharp.",
    unsupportedReason: "Mood-aware adaptation is outside the V4 request boundary.",
  }),
  stressUserCase({
    intentId: "stress-dsa-accountability-unsupported",
    domainId: "coding-interview-patterns",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["cadence"],
    request: "I also want the system to guilt-trip me if I dodge sessions and text a friend if I skip too much.",
    unsupportedReason: "Accountability and social escalation are outside the V4 track-policy boundary.",
  }),
];

const writingStressCases: TrackBenchmarkCaseV4[] = [
  stressUserCase({
    intentId: "stress-writing-clarity-only-rambly",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["scope"],
    request: "My prose keeps getting muddy in exactly the same way, so for a while I'd rather just camp on clarity and stop pretending I'm balancing everything gracefully.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["clarity"], excludeSkillIds: [], includeCategories: ["style"], excludeCategories: [] },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-argument-over-evidence",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["scope", "allocation"],
    request: "Tilt this toward argument over evidence. Not wildly, but enough that 70/30 would be about right.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["argument", "evidence"], excludeSkillIds: [], includeCategories: ["rhetoric"], excludeCategories: [] },
      allocation: { skillWeights: { argument: 0.7, evidence: 0.3 } },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-workday-weekend-window",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["pacing"],
    request: "Weekdays are cramped, so assume 10 there. Weekends are where I can actually breathe, so make those 25.",
    goldPolicy: withPolicy({
      pacing: { weekdayMinutes: 10, weekendMinutes: 25 },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-four-times-week",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["pacing"],
    request: "I can manage four sessions a week if they are short and not fake-busy.",
    goldPolicy: withPolicy({
      pacing: { sessionsPerWeek: 4 },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-more-revisiting-than-fresh",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition", "review"],
    request: "I need more revisiting than fresh prompts right now. New material is just turning into sloppy revision debt.",
    goldPolicy: withPolicy({
      sessionComposition: { reviewShare: 0.7, newShare: 0.3 },
      review: { scheduler: "sm5", aggressiveness: "balanced", interleaveOldAndNew: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-easy-first-then-medium",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty"],
    request: "Don't start with brutal prompts. Ease me in, and then later you can raise it to medium once I'm moving.",
    goldPolicy: withPolicy({
      difficulty: {
        mode: "staged",
        stages: [
          { afterSessions: 0, targetBand: "easy" },
          { afterSessions: 4, maxBand: "medium" },
        ],
      },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-basics-before-fancy",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression", "scope"],
    request: "Before you make this fancy, lock the basics. I don't want higher-level rhetorical flourishes if clarity and structure are still wobbling.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: [], excludeSkillIds: [], includeCategories: [], excludeCategories: [], fundamentalsOnly: true },
      progression: { mode: "mastery_gated", prerequisitesFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-overdue-must-return",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["review"],
    request: "If revision items are overdue, shove them back into the next session until they're handled. Don't let them slip into planner amnesia.",
    goldPolicy: withPolicy({
      review: { scheduler: "sm5", aggressiveness: "aggressive", includeOverdueEverySession: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-drill-cadence",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["cadence", "session_composition"],
    request: "Every third session should be a straight drill block. No wandering, no reflective fluff, just reps.",
    goldPolicy: withPolicy({
      sessionComposition: { drillShare: 0.4 },
      cadence: [{ kind: "every_n_sessions", bucket: "drill", everyNSessions: 3 }],
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-real-first-synthetic-later",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source", "adaptation"],
    request: "Use real examples first. If we run that pool dry, then make synthetic ones, but not until then.",
    goldPolicy: withPolicy({
      adaptation: { onSeedPoolLow: "allow_generation" },
      contentSource: { generatedAllowed: true, generatedOnlyAsFallback: true, realItemsFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-generated-drills-only-no-assessment",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source", "session_composition"],
    request: "Synthetic prompts are fine for drills. They are not fine for anything that feels like assessment or evaluation.",
    goldPolicy: withPolicy({
      sessionComposition: { drillShare: 0.4 },
      contentSource: { generatedAllowed: true, generatedForDrillsOnly: true, noGeneratedForAssessment: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-seed-only-hard-boundary",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source"],
    request: "Keep this on the real catalog only. I do not want synthetic writing prompts sneaking in.",
    goldPolicy: withPolicy({
      contentSource: { seedOnly: true, generatedAllowed: false, realItemsFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-back-off-if-cratering",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty", "adaptation"],
    request: "If I'm faceplanting for a few sessions straight, back the difficulty off instead of pretending the solution is more pressure.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-push-when-cruising",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty", "adaptation"],
    request: "If I'm cruising, then yes, raise the bar. I don't want the planner babying me once it's obvious the current level is too soft.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", pushOnSuccess: true },
      adaptation: { onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-overdue-review-focus",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["adaptation", "session_composition", "review"],
    request: "If overdue revision starts stacking up, shift hard into review focus until that mess is under control.",
    goldPolicy: withPolicy({
      sessionComposition: { reviewShare: 0.8, newShare: 0.2 },
      review: { scheduler: "sm5", aggressiveness: "balanced", includeOverdueEverySession: true },
      adaptation: { onOverdueLoad: "review_focus" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-single-topic-until-solid",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Keep sessions single-topic for now. If we mix style and rhetoric and revision all at once, I stop seeing what's actually broken.",
    goldPolicy: withPolicy({
      sessionComposition: { mixedSessions: false },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-mixed-practice-explicit",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Later I do want mixed practice. I don't want this trapped in little silos forever.",
    goldPolicy: withPolicy({
      sessionComposition: { mixedSessions: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-cap-new-items",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Cap fresh material at 2 new items a session. Past that, the quality falls off a cliff.",
    goldPolicy: withPolicy({
      sessionComposition: { maxNewItemsPerSession: 2 },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-warmup-first-explicit",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Put a warmup at the front. I write noticeably worse if the first thing I see is the hardest prompt.",
    goldPolicy: withPolicy({
      sessionComposition: { warmup: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-breadth-first-pass",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "I want a breadth-first pass before we go deep. Let me touch the territory first, then specialize.",
    goldPolicy: withPolicy({
      progression: { mode: "breadth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-depth-first-pass",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "Go depth-first. I don't want broad exposure if it means every topic stays fuzzy.",
    goldPolicy: withPolicy({
      progression: { mode: "depth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-spiral-looping",
    domainId: "writing-workshop",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "I'd rather keep looping back around than do one neat pass and pretend the problem is solved.",
    goldPolicy: withPolicy({
      progression: { mode: "spiral" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-shaky-stuff-vague",
    domainId: "writing-workshop",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["scope", "allocation", "adaptation"],
    request: "Can you keep me mostly on the shaky bits? I realize that's vague because I'm not even sure how I want 'shaky' defined.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: [], excludeSkillIds: [], includeCategories: [], excludeCategories: [], weakAreasOnly: true },
      allocation: { weakAreaBias: "strong" },
      adaptation: { onRepeatedFailures: "rehab_focus" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-weekends-carry-load-vague",
    domainId: "writing-workshop",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["pacing", "session_composition"],
    request: "Have weekends do more of the lifting. I can't tell you whether that means longer, heavier review, or harder prompts.",
    goldPolicy: withPolicy({
      pacing: { weekendMinutes: 30 },
      sessionComposition: { reviewShare: 0.6 },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-cycle-back-ambiguous",
    domainId: "writing-workshop",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["progression", "review"],
    request: "I want things to cycle back around more, but I mean that in a loose human way, not a precise policy way.",
    goldPolicy: withPolicy({
      progression: { mode: "spiral" },
      review: { scheduler: "sm5", aggressiveness: "balanced", interleaveOldAndNew: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-important-stuff-ambiguous",
    domainId: "writing-workshop",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["scope", "allocation"],
    request: "Stay on the important stuff. That's annoyingly vague, I know, but that's how I'd actually say it.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["argument", "evidence"], excludeSkillIds: [], includeCategories: ["rhetoric"], excludeCategories: [] },
      allocation: { breadthVsDepth: "depth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-turn-it-up-weekends-ambiguous",
    domainId: "writing-workshop",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["pacing", "difficulty"],
    request: "Turn it up on weekends. I mean that emotionally, not as a precise spec.",
    goldPolicy: withPolicy({
      pacing: { weekendMinutes: 40 },
      difficulty: { mode: "fixed", targetBand: "hard" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-more-real-world-ish-ambiguous",
    domainId: "writing-workshop",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["cadence", "difficulty", "session_composition"],
    request: "Can you make this feel more real-world-ish? I can't tell whether I mean assessments, harder prompts, or something else entirely.",
    goldPolicy: withPolicy({
      sessionComposition: { drillShare: 0.4, reviewShare: 0.6 },
      difficulty: { mode: "fixed", targetBand: "hard" },
      cadence: [{ kind: "every_n_sessions", bucket: "drill", everyNSessions: 3 }],
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-push-not-wreck-repair",
    domainId: "writing-workshop",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Push me, just don't wreck me. That's imprecise, but it's still the ask.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-push-not-fry-repair",
    domainId: "writing-workshop",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Stretch me, but don't fry me. I want the pressure, not the collapse.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-honest-but-learning-repair",
    domainId: "writing-workshop",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "review"],
    request: "Be honest about how rough the work is, but don't make the plan punitive. I still need room to learn.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", backoffOnStruggle: true, pushOnSuccess: true },
      review: { scheduler: "sm5", aggressiveness: "balanced" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-challenge-not-underwater-repair",
    domainId: "writing-workshop",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Challenge me, but not so hard that every session feels like drowning.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-writing-tired-after-work-unsupported",
    domainId: "writing-workshop",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "When I'm wiped out after work, have the plan quietly soften itself so I don't need to think about it.",
    unsupportedReason: "Fatigue-aware context is out of scope for deterministic track policy.",
  }),
  stressUserCase({
    intentId: "stress-writing-stress-level-unsupported",
    domainId: "writing-workshop",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "Adjust the plan to my stress level without me explicitly editing anything.",
    unsupportedReason: "Stress-aware adaptation is not represented in V4 track policy.",
  }),
  stressUserCase({
    intentId: "stress-writing-sleep-quality-unsupported",
    domainId: "writing-workshop",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["pacing"],
    request: "If I slept badly, I want the day to be lighter automatically.",
    unsupportedReason: "Sleep-aware pacing is outside the V4 request boundary.",
  }),
  stressUserCase({
    intentId: "stress-writing-calendar-unsupported",
    domainId: "writing-workshop",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["cadence", "pacing"],
    request: "Use my calendar and move the writing plan around deadlines and meetings without me micromanaging it.",
    unsupportedReason: "External calendar state is not modeled in V4 track policy.",
  }),
  stressUserCase({
    intentId: "stress-writing-mood-unsupported",
    domainId: "writing-workshop",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "Make it lighter when I'm in a bad mood and sharper when I'm in a good one.",
    unsupportedReason: "Mood-aware adaptation is outside the V4 request boundary.",
  }),
  stressUserCase({
    intentId: "stress-writing-accountability-unsupported",
    domainId: "writing-workshop",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["cadence"],
    request: "If I ghost sessions, start nagging me and maybe shame me a little so I stay on track.",
    unsupportedReason: "Accountability and coach-style behavior are outside the V4 track-policy boundary.",
  }),
];

const languageStressCases: TrackBenchmarkCaseV4[] = [
  stressUserCase({
    intentId: "stress-language-vocab-only-rambly",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["scope"],
    request: "My vocab is obviously the hole, so for a while just camp there and stop pretending I'm balancing every skill equally.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["vocabulary"], excludeSkillIds: [], includeCategories: ["lexicon"], excludeCategories: [] },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-listening-over-speaking",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["scope", "allocation"],
    request: "Tilt this more toward listening than speaking. If you need numbers, 70/30 feels close enough.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["listening", "speaking"], excludeSkillIds: [], includeCategories: ["comprehension", "production"], excludeCategories: [] },
      allocation: { skillWeights: { listening: 0.7, speaking: 0.3 } },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-workday-weekend-window",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["pacing"],
    request: "I can manage maybe 12 on weekdays. Weekends are where I have actual room, so put 24 there.",
    goldPolicy: withPolicy({
      pacing: { weekdayMinutes: 12, weekendMinutes: 24 },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-four-times-week",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["pacing"],
    request: "Four sessions a week is realistic. More than that and this stops being sustainable.",
    goldPolicy: withPolicy({
      pacing: { sessionsPerWeek: 4 },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-more-recycling-than-new",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition", "review"],
    request: "I need more recycling than new material right now. If it's mostly fresh input, the old stuff evaporates.",
    goldPolicy: withPolicy({
      sessionComposition: { reviewShare: 0.7, newShare: 0.3 },
      review: { scheduler: "sm5", aggressiveness: "balanced", interleaveOldAndNew: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-easy-first-then-medium",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty"],
    request: "Don't start by frying me. Go easy first, and then later move it up to medium once I'm moving.",
    goldPolicy: withPolicy({
      difficulty: {
        mode: "staged",
        stages: [
          { afterSessions: 0, targetBand: "easy" },
          { afterSessions: 4, maxBand: "medium" },
        ],
      },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-basics-before-fancy",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression", "scope"],
    request: "Before you make this fancy, lock grammar and vocab. I don't want advanced production work if the foundations are still loose.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: [], excludeSkillIds: [], includeCategories: [], excludeCategories: [], fundamentalsOnly: true },
      progression: { mode: "mastery_gated", prerequisitesFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-overdue-must-return",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["review"],
    request: "If review is overdue, drag it back until it's handled. Don't let the planner quietly bury it.",
    goldPolicy: withPolicy({
      review: { scheduler: "sm5", aggressiveness: "aggressive", includeOverdueEverySession: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-drill-cadence",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["cadence", "session_composition"],
    request: "Every third session should be drill-heavy. I still want normal sessions too, but the rhythm should be there.",
    goldPolicy: withPolicy({
      sessionComposition: { drillShare: 0.4 },
      cadence: [{ kind: "every_n_sessions", bucket: "drill", everyNSessions: 3 }],
    }),
  }),
  stressUserCase({
    intentId: "stress-language-real-first-synthetic-later",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source", "adaptation"],
    request: "Use real material first. If the pool gets thin, then generate extras. Not before.",
    goldPolicy: withPolicy({
      adaptation: { onSeedPoolLow: "allow_generation" },
      contentSource: { generatedAllowed: true, generatedOnlyAsFallback: true, realItemsFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-generated-drills-only-no-assessment",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source", "session_composition"],
    request: "Synthetic items are fine for drills. They are not fine for anything that counts as assessment.",
    goldPolicy: withPolicy({
      sessionComposition: { drillShare: 0.4 },
      contentSource: { generatedAllowed: true, generatedForDrillsOnly: true, noGeneratedForAssessment: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-seed-only-hard-boundary",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["content_source"],
    request: "Keep this on real material only. No synthetic filler sneaking in because the pool got small.",
    goldPolicy: withPolicy({
      contentSource: { seedOnly: true, generatedAllowed: false, realItemsFirst: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-back-off-if-cratering",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty", "adaptation"],
    request: "If I'm bombing repeatedly, back it off. I don't want the system reacting by turning the screw tighter.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-push-when-cruising",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["difficulty", "adaptation"],
    request: "If I'm cruising, then yes, push harder. I don't want the planner preserving easy mode out of politeness.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", pushOnSuccess: true },
      adaptation: { onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-overdue-review-focus",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["adaptation", "session_composition", "review"],
    request: "If overdue review starts stacking up, shift hard into review focus. Stop chasing novelty until the backlog comes down.",
    goldPolicy: withPolicy({
      sessionComposition: { reviewShare: 0.8, newShare: 0.2 },
      review: { scheduler: "sm5", aggressiveness: "balanced", includeOverdueEverySession: true },
      adaptation: { onOverdueLoad: "review_focus" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-single-topic-until-solid",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Keep sessions single-topic for a while. If we mix too much, I lose track of what is actually slipping.",
    goldPolicy: withPolicy({
      sessionComposition: { mixedSessions: false },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-mixed-practice-explicit",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Later I do want mixed practice. I don't want each session trapped in its own lane forever.",
    goldPolicy: withPolicy({
      sessionComposition: { mixedSessions: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-cap-new-items",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Cap fresh material at 2 new items per session. Beyond that, retention gets sloppy fast.",
    goldPolicy: withPolicy({
      sessionComposition: { maxNewItemsPerSession: 2 },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-warmup-first-explicit",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["session_composition"],
    request: "Give me a warmup first. I don't want the first contact point of the day to be the hardest task.",
    goldPolicy: withPolicy({
      sessionComposition: { warmup: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-breadth-first-pass",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "I want a breadth-first pass before we specialize. Let me touch the system before we dig deep into one thing.",
    goldPolicy: withPolicy({
      progression: { mode: "breadth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-depth-first-pass",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "No survey mode. Go depth-first and stay there long enough for real traction.",
    goldPolicy: withPolicy({
      progression: { mode: "depth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-spiral-looping",
    domainId: "language-lab",
    benchmarkClass: "supported",
    expectedOutcome: "compiled",
    policyFamilies: ["progression"],
    request: "I'd rather keep looping back around than do one pass and pretend the topic is now solved forever.",
    goldPolicy: withPolicy({
      progression: { mode: "spiral" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-shaky-stuff-vague",
    domainId: "language-lab",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["scope", "allocation", "adaptation"],
    request: "Could you mostly keep me on the shaky parts? I'm not sure whether I mean confidence, misses, or overdue review though.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: [], excludeSkillIds: [], includeCategories: [], excludeCategories: [], weakAreasOnly: true },
      allocation: { weakAreaBias: "strong" },
      adaptation: { onRepeatedFailures: "rehab_focus" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-weekends-carry-load-vague",
    domainId: "language-lab",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["pacing", "session_composition"],
    request: "Have weekends carry more of the load. I don't actually know whether that means longer sessions, more review, or harder work.",
    goldPolicy: withPolicy({
      pacing: { weekendMinutes: 30 },
      sessionComposition: { reviewShare: 0.6 },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-cycle-back-ambiguous",
    domainId: "language-lab",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["progression", "review"],
    request: "I want things to cycle back around more, but I'm describing that like a human, not a specification writer.",
    goldPolicy: withPolicy({
      progression: { mode: "spiral" },
      review: { scheduler: "sm5", aggressiveness: "balanced", interleaveOldAndNew: true },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-important-stuff-ambiguous",
    domainId: "language-lab",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["scope", "allocation"],
    request: "Stay on the important stuff. That's too vague, I know, but that's really how I'd phrase it.",
    goldPolicy: withPolicy({
      scope: { includeSkillIds: ["grammar", "vocabulary"], excludeSkillIds: [], includeCategories: ["grammar", "lexicon"], excludeCategories: [] },
      allocation: { breadthVsDepth: "depth_first" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-turn-it-up-weekends-ambiguous",
    domainId: "language-lab",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["pacing", "difficulty"],
    request: "Turn it up on weekends. I mean that emotionally, not as an actual policy spec.",
    goldPolicy: withPolicy({
      pacing: { weekendMinutes: 40 },
      difficulty: { mode: "fixed", targetBand: "hard" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-more-native-ish-ambiguous",
    domainId: "language-lab",
    benchmarkClass: "ambiguous",
    expectedOutcome: "clarify",
    policyFamilies: ["cadence", "difficulty", "session_composition"],
    request: "Can you make this feel more native-ish? I don't know whether that means harder output, more speaking, or something else.",
    goldPolicy: withPolicy({
      sessionComposition: { drillShare: 0.4, reviewShare: 0.6 },
      difficulty: { mode: "fixed", targetBand: "hard" },
      cadence: [{ kind: "every_n_sessions", bucket: "drill", everyNSessions: 3 }],
    }),
  }),
  stressUserCase({
    intentId: "stress-language-push-not-wreck-repair",
    domainId: "language-lab",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Push me, just don't wreck me. I know that's not proper taxonomy language, but that's what I mean.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-push-not-fry-repair",
    domainId: "language-lab",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Stretch me, but don't fry me. I want challenge without getting smoked every session.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-honest-but-learning-repair",
    domainId: "language-lab",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "review"],
    request: "Be honest about how rough my output is, but don't make the plan punitive. I still need room to learn.",
    goldPolicy: withPolicy({
      difficulty: { mode: "adaptive", backoffOnStruggle: true, pushOnSuccess: true },
      review: { scheduler: "sm5", aggressiveness: "balanced" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-challenge-not-underwater-repair",
    domainId: "language-lab",
    benchmarkClass: "repairable",
    expectedOutcome: "repaired",
    policyFamilies: ["difficulty", "adaptation", "pacing"],
    request: "Challenge me, but not so hard that I feel underwater every time I open the app.",
    goldPolicy: withPolicy({
      pacing: { intensity: "steady" },
      difficulty: { mode: "adaptive", pushOnSuccess: true, backoffOnStruggle: true },
      adaptation: { onRepeatedFailures: "reduce_difficulty", onCleanStreak: "advance_difficulty" },
    }),
  }),
  stressUserCase({
    intentId: "stress-language-tired-after-work-unsupported",
    domainId: "language-lab",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "When I'm wiped out after work, just have the plan soften itself automatically.",
    unsupportedReason: "Fatigue-aware context is out of scope for deterministic track policy.",
  }),
  stressUserCase({
    intentId: "stress-language-stress-level-unsupported",
    domainId: "language-lab",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "Match the plan to my stress level in the background without me needing to toggle anything.",
    unsupportedReason: "Stress-aware adaptation is not represented in V4 track policy.",
  }),
  stressUserCase({
    intentId: "stress-language-sleep-quality-unsupported",
    domainId: "language-lab",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["pacing"],
    request: "If I slept badly, make the day lighter automatically.",
    unsupportedReason: "Sleep-aware pacing is outside the V4 request boundary.",
  }),
  stressUserCase({
    intentId: "stress-language-calendar-unsupported",
    domainId: "language-lab",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["cadence", "pacing"],
    request: "Use my calendar and rearrange the language plan around appointments and travel.",
    unsupportedReason: "External calendar state is not modeled in V4 track policy.",
  }),
  stressUserCase({
    intentId: "stress-language-mood-unsupported",
    domainId: "language-lab",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["difficulty"],
    request: "Make output work lighter when I'm in a bad mood and sharper when I'm feeling great.",
    unsupportedReason: "Mood-aware adaptation is outside the V4 request boundary.",
  }),
  stressUserCase({
    intentId: "stress-language-accountability-unsupported",
    domainId: "language-lab",
    benchmarkClass: "unsupported",
    expectedOutcome: "reject",
    policyFamilies: ["cadence"],
    request: "If I dodge sessions, start nagging me and maybe ping someone so I feel accountable.",
    unsupportedReason: "Accountability and social escalation are outside the V4 track-policy boundary.",
  }),
];

export const TRACK_V4_STRESS_USER_CASES: TrackBenchmarkCaseV4[] = [
  ...codingStressCases,
  ...writingStressCases,
  ...languageStressCases,
];

export function summarizeStressUserCasesV4(): TrackBenchmarkSummaryV4 {
  const byClass: TrackBenchmarkSummaryV4["byClass"] = {
    supported: 0,
    ambiguous: 0,
    repairable: 0,
    unsupported: 0,
  };
  const byDomain: TrackBenchmarkSummaryV4["byDomain"] = {
    "coding-interview-patterns": 0,
    "writing-workshop": 0,
    "language-lab": 0,
  };

  for (const benchmarkCase of TRACK_V4_STRESS_USER_CASES) {
    byClass[benchmarkCase.benchmarkClass] += 1;
    byDomain[benchmarkCase.domainId] += 1;
  }

  return {
    total: TRACK_V4_STRESS_USER_CASES.length,
    byClass,
    byDomain,
  };
}
