import type { LearnspaceFamilyDefinition } from "./types.js";

export const dsaFamily: LearnspaceFamilyDefinition = {
  id: "dsa",
  label: "DSA",
  description: "Coding interview problem solving with an editor, tests, and structured solve protocol.",
  archetypes: ["protocol_solve"],
  moduleIds: [
    "problem_view",
    "step_protocol",
    "code_editor",
    "test_runner",
    "coach_panel",
    "reflection_panel",
  ],
  artifactKinds: [
    "problem",
    "hint",
    "reference_solution",
    "reflection_note",
  ],
  protocolStepIds: [
    "understanding",
    "approach",
    "key_insight",
    "walkthrough",
    "code",
    "verify",
    "reflect",
  ],
  validatorKinds: ["code_executor"],
  schedulerIds: ["sm5"],
  sessionTypes: [
    "timed_solve",
    "untimed_solve",
    "review_drill",
    "mock",
    "recall",
    "recap",
    "concept_quiz",
    "application",
  ],
  evaluatorKinds: ["correctness", "communication", "recall", "code_executor"],
  scopeDimensions: ["skill", "tag", "source"],
  difficultyBands: ["easy", "medium", "hard"],
  styleDimensions: ["company_style", "exam_style", "practical_style"],
  generationCapabilities: {
    supportedArtifactKinds: ["problem", "hint", "reflection_note"],
    supportsStyleTargeting: true,
    supportsNoveltyTargeting: true,
    supportsDifficultyTargeting: true,
  },
  evidenceDimensions: [
    "mistake_pattern",
    "strength_signal",
    "communication_signal",
    "difficulty_mismatch",
    "novelty_tolerance",
    "fatigue_or_avoidance",
    "readiness_signal",
    "confidence_calibration",
  ],
};
